services: 
  db:
    image: postgres:18-alpine # (Te recomiendo fijar la versi√≥n)
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    container_name: finoradb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: